name: Dashboard Issue Report
description: Report a bug, suggest a feature, or request an enhancement for the website
title: "[Dashboard] Brief Summary of Issue"
labels: [triage]
assignees: [herobuxx, yoginara]

body:
- type: dropdown
  attributes:
    label: Issue Type
    description: "Select the type of issue you're reporting."
    options:
      - Bug Report
      - Feature Request
      - Enhancement
  validations:
    required: true

- type: input
  attributes:
    label: Issue Summary
    description: "Provide a brief summary of the issue."
  validations:
    required: true

- type: textarea
  attributes:
    label: Description
    description: "Give a detailed description of the issue, including steps to reproduce for bugs."
  validations:
    required: true

- type: textarea
  attributes:
    label: Expected Result (for Bug Reports)
    description: "Describe what you expected to happen."
  validations:
    required: false

- type: textarea
  attributes:
    label: Actual Result (for Bug Reports)
    description: "Describe what actually happened."
  validations:
    required: false

- type: textarea
  attributes:
    label: Feature/Enhancement Description (for Feature Requests)
    description: "Describe the feature or enhancement you'd like to see and its purpose."
  validations:
    required: false

- type: textarea
  attributes:
    label: Additional Information
    description: "Provide any other information, screenshots, or context that might help."
  validations:
    required: false
